### ISSUE TITLE
DOM side effects when importing module

### ISSUE THREAD

**Issue by aendrew** [Financial-Times/o-ads#169]
Hi! 

I'm using o-ads in a SSR React context on IG projects and o-ads is breaking the server process by calling DOM methods on module import, meaning I can't defer DOM work in React via `componentDidMount()`. 

Would it be possible to put all DOM methods inside of functions so they only get called once needed?

**Comment by alexflorisca** [comment]
@aendrew I think because o-ads is an origami component, it needs to attach some event handlers as soon as it's required in order to work out of the box with the origami build service. I think all components follow the same idea. This is the audio one as an example: https://github.com/Financial-Times/o-audio/blob/master/main.js

I used react a few years ago so my knowledge of it is a little hazy - but is there any react specific thing we can detect in the dom in order to skip adding the event handlers maybe?

**Comment by aendrew** [comment]
@alexflorisca In general, yes, main.js adds event listeners to `o.DOMContentLoaded`, but this can be gotten around in a SSR context by importing `src/<componentName>.js` instead, provided that file just exports functions and doesn't cause DOM side-effects on import. The DOM-manipulating operations can then be called inside `componentDidMount()` once it's loaded in a browser

Honestly though I've gotten it working by shimming the relevant DOM methods in my application so it's probably less of an issue; see linked PR above for the approach. 

Closing issue as such.
